// <auto-generated />
using System;
using GameBaseSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameBaseSite.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20211206145557_Fifth")]
    partial class Fifth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameBaseSite.Models.GameModel", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EsrbRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Review")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserRating")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            EsrbRating = "M",
                            Genre = "First Person Shooter",
                            Review = "",
                            Status = "",
                            Title = "Quake",
                            Type = "Power",
                            UserRating = 10
                        },
                        new
                        {
                            GameId = 2,
                            EsrbRating = "M",
                            Genre = "Paradox Grand Strategy",
                            Review = "",
                            Status = "",
                            Title = "Crusader Kings III",
                            Type = "Brainy",
                            UserRating = 9
                        },
                        new
                        {
                            GameId = 3,
                            EsrbRating = "T",
                            Genre = "Casino Games",
                            Review = "",
                            Status = "",
                            Title = "Vegas Casino Collections",
                            Type = "Casual",
                            UserRating = 5
                        },
                        new
                        {
                            GameId = 4,
                            EsrbRating = "E",
                            Genre = "2d Platformer",
                            Review = "",
                            Status = "",
                            Title = "Waluigi World 2",
                            Type = "OldSchool",
                            UserRating = 10
                        },
                        new
                        {
                            GameId = 5,
                            EsrbRating = "M",
                            Genre = "Survival Horro, First Person Shooter",
                            Review = "",
                            Status = "",
                            Title = "Escape From Tarkov",
                            Type = "Power",
                            UserRating = 9
                        },
                        new
                        {
                            GameId = 6,
                            EsrbRating = "E",
                            Genre = "Tower Defense",
                            Review = "",
                            Status = "",
                            Title = "Bloons TD -1",
                            Type = "Casual",
                            UserRating = 7
                        },
                        new
                        {
                            GameId = 7,
                            EsrbRating = "T",
                            Genre = "Adventure Puzzle",
                            Review = "",
                            Status = "",
                            Title = "The Initiate",
                            Type = "Brainy",
                            UserRating = 6
                        },
                        new
                        {
                            GameId = 8,
                            EsrbRating = "E",
                            Genre = "Arcade",
                            Review = "",
                            Status = "",
                            Title = "Mr.Peck-Mon",
                            Type = "OldSchool",
                            UserRating = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
