// <auto-generated />
using GameBaseSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameBaseSite.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20211208154932_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameBaseSite.Models.GameModel", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EsrbRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = "1",
                            EsrbRating = "M",
                            Genre = "First Person Shooter",
                            Title = "Quake",
                            Type = "Power"
                        },
                        new
                        {
                            GameId = "2",
                            EsrbRating = "M",
                            Genre = "Paradox Grand Strategy",
                            Title = "Crusader Kings III",
                            Type = "Brainy"
                        },
                        new
                        {
                            GameId = "3",
                            EsrbRating = "T",
                            Genre = "Casino Games",
                            Title = "Vegas Casino Collections",
                            Type = "Casual"
                        },
                        new
                        {
                            GameId = "4",
                            EsrbRating = "E",
                            Genre = "2d Platformer",
                            Title = "Waluigi World 2",
                            Type = "OldSchool"
                        },
                        new
                        {
                            GameId = "5",
                            EsrbRating = "M",
                            Genre = "Survival Horror",
                            Title = "Escape From Tarkov",
                            Type = "Power"
                        },
                        new
                        {
                            GameId = "6",
                            EsrbRating = "E",
                            Genre = "Tower Defense",
                            Title = "Bloons TD -1",
                            Type = "Casual"
                        },
                        new
                        {
                            GameId = "7",
                            EsrbRating = "T",
                            Genre = "Adventure Puzzle",
                            Title = "The Initiate",
                            Type = "Brainy"
                        },
                        new
                        {
                            GameId = "8",
                            EsrbRating = "E",
                            Genre = "Arcade",
                            Title = "Mr.Peck-Mon",
                            Type = "OldSchool"
                        });
                });

            modelBuilder.Entity("GameBaseSite.Models.ProfileGameModel", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EsrbRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("GameId");

                    b.ToTable("ProfileGames");

                    b.HasData(
                        new
                        {
                            GameId = "4",
                            EsrbRating = "E",
                            Genre = "2d Platformer",
                            Title = "Waluigi World 2",
                            Type = "OldSchool"
                        },
                        new
                        {
                            GameId = "5",
                            EsrbRating = "M",
                            Genre = "Survival Horror",
                            Title = "Escape From Tarkov",
                            Type = "Power"
                        },
                        new
                        {
                            GameId = "2",
                            EsrbRating = "M",
                            Genre = "Paradox Grand Strategy",
                            Title = "Crusader Kings III",
                            Type = "Brainy"
                        },
                        new
                        {
                            GameId = "3",
                            EsrbRating = "T",
                            Genre = "Casino Games",
                            Title = "Vegas Casino Collections",
                            Type = "Casual"
                        });
                });

            modelBuilder.Entity("GameBaseSite.Models.UserGameModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "GameId");

                    b.ToTable("UsrGames");

                    b.HasData(
                        new
                        {
                            UserId = "222",
                            GameId = "1",
                            Title = "Quake"
                        },
                        new
                        {
                            UserId = "111",
                            GameId = "2",
                            Title = "Crusader Kings III"
                        },
                        new
                        {
                            UserId = "111",
                            GameId = "5",
                            Title = "Escape From Tarkov"
                        },
                        new
                        {
                            UserId = "222",
                            GameId = "2",
                            Title = "Crusader Kings III"
                        },
                        new
                        {
                            UserId = "222",
                            GameId = "4",
                            Title = "Waluigi World 2"
                        },
                        new
                        {
                            UserId = "111",
                            GameId = "7",
                            Title = "The Initiate"
                        },
                        new
                        {
                            UserId = "333",
                            GameId = "6",
                            Title = "Bloons TD -1"
                        },
                        new
                        {
                            UserId = "333",
                            GameId = "3",
                            Title = "Vegas Casino Collections"
                        },
                        new
                        {
                            UserId = "444",
                            GameId = "8",
                            Title = "Mr.Peck-Mon"
                        },
                        new
                        {
                            UserId = "444",
                            GameId = "4",
                            Title = "Waluigi World 2"
                        },
                        new
                        {
                            UserId = "444",
                            GameId = "1",
                            Title = "Quake"
                        });
                });

            modelBuilder.Entity("GameBaseSite.Models.UserModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FavoriteGame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = "111",
                            FavoriteGame = "PC Building Simulator",
                            PlayStyle = "Power",
                            UserName = "GameDude01"
                        },
                        new
                        {
                            UserId = "222",
                            FavoriteGame = "The Impossible Game",
                            PlayStyle = "Brainy",
                            UserName = "starchild"
                        },
                        new
                        {
                            UserId = "333",
                            FavoriteGame = "Candy Crush",
                            PlayStyle = "Casual",
                            UserName = "MomOfThree"
                        },
                        new
                        {
                            UserId = "444",
                            FavoriteGame = "Asteroids",
                            PlayStyle = "OldSchool",
                            UserName = "corvetteFan1963"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
